// <auto-generated />
using System;
using InternationalPaymentsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternationalPaymentsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606124346_AddEmployeeSessions")]
    partial class AddEmployeeSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternationalPaymentsAPI.Models.BeneficiaryModel", b =>
                {
                    b.Property<int>("beneficiary_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("beneficiary_Id"));

                    b.Property<string>("account_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("account_Number");

                    b.Property<string>("bank_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_Name");

                    b.Property<string>("beneficiary_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("beneficiary_Name");

                    b.Property<string>("country")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country");

                    b.Property<int>("customer_Id")
                        .HasColumnType("int")
                        .HasColumnName("customer_Id");

                    b.Property<string>("swift_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("swift_Code");

                    b.HasKey("beneficiary_Id");

                    b.HasIndex("customer_Id");

                    b.ToTable("tblBeneficiary", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerModel", b =>
                {
                    b.Property<int>("customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("account_Number")
                        .HasColumnType("int")
                        .HasColumnName("account_Number");

                    b.Property<string>("email_Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_Address");

                    b.Property<string>("first_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_Name");

                    b.Property<string>("id_Number")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("id_Number");

                    b.Property<string>("last_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_Name");

                    b.Property<string>("password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("preferred_Currency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferred_Currency");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("customer_Id");

                    b.ToTable("tblCustomer", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerSessionModel", b =>
                {
                    b.Property<int>("session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("session_Id"));

                    b.Property<int>("customer_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expires_On")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("login_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("logout_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("session_Token_Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("session_Id");

                    b.HasIndex("customer_Id");

                    b.HasIndex("session_Token_Hash")
                        .IsUnique();

                    b.ToTable("tblCustomerSession", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.EmployeeModel", b =>
                {
                    b.Property<int>("employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_Id"));

                    b.Property<string>("full_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("is_Active")
                        .HasColumnType("bit");

                    b.Property<string>("password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("employee_Id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("tblEmployee", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.EmployeeSessionModel", b =>
                {
                    b.Property<int>("employee_Session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_Session_Id"));

                    b.Property<int>("employee_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expires_On")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("login_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("logout_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("session_Token_Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("employee_Session_Id");

                    b.HasIndex("employee_Id");

                    b.HasIndex("session_Token_Hash")
                        .IsUnique();

                    b.ToTable("tblEmployeeSession", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.MfaChallengeModel", b =>
                {
                    b.Property<Guid>("mfa_Challenge_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mfa_Challenge_Id");

                    b.Property<int>("attempt_Count")
                        .HasColumnType("int")
                        .HasColumnName("attempt_Count");

                    b.Property<DateTime?>("consumed_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("consumed_On");

                    b.Property<DateTime>("created_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On");

                    b.Property<int>("customer_Id")
                        .HasColumnType("int")
                        .HasColumnName("customer_Id");

                    b.Property<DateTime>("expires_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_On");

                    b.Property<string>("otp_Code_Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("otp_Code_Hash");

                    b.HasKey("mfa_Challenge_Id");

                    b.HasIndex("customer_Id");

                    b.ToTable("tblMfaChallenge", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.PaymentModel", b =>
                {
                    b.Property<int>("payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payment_Id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("beneficiary_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("customer_Id")
                        .HasColumnType("int");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("submitted_To_Swift_On")
                        .HasColumnType("datetime2");

                    b.Property<string>("swift_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("verified_By_Employee_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("verified_On")
                        .HasColumnType("datetime2");

                    b.HasKey("payment_Id");

                    b.HasIndex("beneficiary_Id");

                    b.HasIndex("customer_Id");

                    b.HasIndex("verified_By_Employee_Id");

                    b.ToTable("tblPayment", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.BeneficiaryModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerSessionModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany("CustomerSessions")
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.EmployeeSessionModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.MfaChallengeModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany("MfaChallenges")
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.PaymentModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.BeneficiaryModel", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("beneficiary_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternationalPaymentsAPI.Models.EmployeeModel", "VerifiedByEmployee")
                        .WithMany()
                        .HasForeignKey("verified_By_Employee_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Beneficiary");

                    b.Navigation("Customer");

                    b.Navigation("VerifiedByEmployee");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerModel", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("CustomerSessions");

                    b.Navigation("MfaChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
