// <auto-generated />
using System;
using InternationalPaymentsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternationalPaymentsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternationalPaymentsAPI.Models.BeneficiaryModel", b =>
                {
                    b.Property<int>("beneficiary_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("beneficiary_Id"));

                    b.Property<string>("account_Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("account_Number");

                    b.Property<string>("bank_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_Name");

                    b.Property<string>("beneficiary_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("beneficiary_Name");

                    b.Property<string>("country")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country");

                    b.Property<int>("customer_Id")
                        .HasColumnType("int")
                        .HasColumnName("customer_Id");

                    b.Property<string>("swift_Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("swift_Code");

                    b.HasKey("beneficiary_Id");

                    b.HasIndex("customer_Id");

                    b.ToTable("tblBeneficiary", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerModel", b =>
                {
                    b.Property<int>("customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("account_Number")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("account_Number");

                    b.Property<string>("email_Address")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_Address");

                    b.Property<string>("first_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_Name");

                    b.Property<string>("id_Number")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("id_Number");

                    b.Property<string>("last_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_Name");

                    b.Property<string>("password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("preferred_Currency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferred_Currency");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("customer_Id");

                    b.ToTable("tblCustomer", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerSessionModel", b =>
                {
                    b.Property<int>("session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("session_Id"));

                    b.Property<int>("customer_Id")
                        .HasColumnType("int");

                    b.Property<bool>("is_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("login_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("logout_Time")
                        .HasColumnType("datetime2");

                    b.HasKey("session_Id");

                    b.HasIndex("customer_Id");

                    b.ToTable("tblCustomerSession", (string)null);
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.BeneficiaryModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerSessionModel", b =>
                {
                    b.HasOne("InternationalPaymentsAPI.Models.CustomerModel", "Customer")
                        .WithMany("CustomerSessions")
                        .HasForeignKey("customer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InternationalPaymentsAPI.Models.CustomerModel", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("CustomerSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
