sonar.projectKey=BongumusaCele_International-Payments-App-Service
sonar.organization=bongumusacele
sonar.host.url=https://sonarcloud.io
sonar.sources=InternationalPaymentsAPI
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**,**/*.Designer.cs,**/*.g.cs
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
